version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim_nginx:
        image: nginx:alpine
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/
            - ./public:/var/www/moji-chat-php/public
        ports:
            - 8080:80
        depends_on:
            - slim
        networks:
            - slim_net
    slim:
        build:
          context: .
          dockerfile: ./Dockerfile
        volumes:
            - ./:/var/www/html
        networks:
            - slim_net
    moji-cache:
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - slim_net
networks:
    slim_net:
        driver: bridge
